modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0-only"

[[mods]]
modId="squadtp"
version="${file.jarVersion}"
displayName="Squad Teleport"
description='''Squad (party) system with member teleport and optional JourneyMap integration.'''

[[dependencies.squadtp]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.244,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.squadtp]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
